var data = [
    {
      "total": 1,
      "unidadeEnsino": "",
      "unidadeFisica": "001",
      "ano": 2014,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "PUBL",
      "nomeCurso": "Publicidade e Propaganda",
      "serie": "3",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2014/1"
    },
    {
      "total": 1,
      "unidadeEnsino": "",
      "unidadeFisica": "001",
      "ano": 2014,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "PUBL",
      "nomeCurso": "Publicidade e Propaganda",
      "serie": "6",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2014/1"
    },
    {
      "total": 1,
      "unidadeEnsino": "",
      "unidadeFisica": "001",
      "ano": 2014,
      "periodo": 2,
      "tipo": "LATO",
      "descricao": "LATO-SENSU",
      "curso": "PG-CB",
      "nomeCurso": "ESPECIALIZAÇÃO EM TEORIAS E PRÁTICAS DA COMUNICAÇÃO",
      "serie": "1",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2014/2"
    },
    {
      "total": 1,
      "unidadeEnsino": "",
      "unidadeFisica": "001",
      "ano": 2015,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "PUBL",
      "nomeCurso": "Publicidade e Propaganda",
      "serie": "8",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2015/1"
    },
    {
      "total": 1,
      "unidadeEnsino": "",
      "unidadeFisica": "002",
      "ano": 2014,
      "periodo": 0,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "JOR",
      "nomeCurso": "JORNALISMO",
      "serie": "1",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2014/0"
    },
    {
      "total": 23,
      "unidadeEnsino": "",
      "unidadeFisica": "002",
      "ano": 2016,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "12",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2016/1"
    },
    {
      "total": 8,
      "unidadeEnsino": "",
      "unidadeFisica": "003",
      "ano": 2004,
      "periodo": 0,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "8",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2004/0"
    },
    {
      "total": 25,
      "unidadeEnsino": "",
      "unidadeFisica": "003",
      "ano": 2004,
      "periodo": 0,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "202",
      "nomeCurso": "Pedagogia | Por Crédito Presencial",
      "serie": "6",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2004/0"
    },
    {
      "total": 25,
      "unidadeEnsino": "",
      "unidadeFisica": "003",
      "ano": 2005,
      "periodo": 0,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "202",
      "nomeCurso": "Pedagogia | Por Crédito Presencial",
      "serie": "6",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2005/0"
    },
    {
      "total": 12,
      "unidadeEnsino": "",
      "unidadeFisica": "003",
      "ano": 2006,
      "periodo": 0,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "202",
      "nomeCurso": "Pedagogia | Por Crédito Presencial",
      "serie": "6",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2006/0"
    },
    {
      "total": 23,
      "unidadeEnsino": "",
      "unidadeFisica": "003",
      "ano": 2016,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "8",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2016/1"
    },
    {
      "total": 16,
      "unidadeEnsino": "",
      "unidadeFisica": "003",
      "ano": 2016,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "202",
      "nomeCurso": "Pedagogia | Por Crédito Presencial",
      "serie": "6",
      "tipoHist": "EVADIDOS",
      "anoPeriodo": "2016/1"
    },
    {
      "total": 1,
      "unidadeEnsino": "1",
      "unidadeFisica": "null",
      "ano": 2017,
      "periodo": 0,
      "tipo": "EF",
      "descricao": "ENSINO FUNDAMENTAL",
      "curso": "EF",
      "nomeCurso": "Ensino Fundamental",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/0"
    },
    {
      "total": 1,
      "unidadeEnsino": "1",
      "unidadeFisica": "001",
      "ano": 2017,
      "periodo": 0,
      "tipo": "EF",
      "descricao": "ENSINO FUNDAMENTAL",
      "curso": "EF",
      "nomeCurso": "Ensino Fundamental",
      "serie": "2",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/0"
    },
    {
      "total": 51,
      "unidadeEnsino": "1",
      "unidadeFisica": "001",
      "ano": 2017,
      "periodo": 0,
      "tipo": "EM",
      "descricao": "ENSINO MÉDIO",
      "curso": "EM",
      "nomeCurso": "Ensino Médio",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/0"
    },
    {
      "total": 1,
      "unidadeEnsino": "2",
      "unidadeFisica": "null",
      "ano": 2017,
      "periodo": 1,
      "tipo": "MBA",
      "descricao": "MBA",
      "curso": "MKT-MBA",
      "nomeCurso": "MBA EM MARKETING",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 59,
      "unidadeEnsino": "2",
      "unidadeFisica": "null",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "PUBL",
      "nomeCurso": "Publicidade e Propaganda",
      "serie": "6",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 1,
      "unidadeEnsino": "2",
      "unidadeFisica": "001",
      "ano": 2014,
      "periodo": 0,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "JOR",
      "nomeCurso": "JORNALISMO",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2014/0"
    },
    {
      "total": 2,
      "unidadeEnsino": "2",
      "unidadeFisica": "001",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "2",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 1,
      "unidadeEnsino": "2",
      "unidadeFisica": "001",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "4",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 1,
      "unidadeEnsino": "2",
      "unidadeFisica": "001",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "PUBL",
      "nomeCurso": "Publicidade e Propaganda",
      "serie": "2",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 16,
      "unidadeEnsino": "2",
      "unidadeFisica": "001",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "PUBL",
      "nomeCurso": "Publicidade e Propaganda",
      "serie": "6",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 15,
      "unidadeEnsino": "2",
      "unidadeFisica": "001",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "PUBL",
      "nomeCurso": "Publicidade e Propaganda",
      "serie": "7",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 59,
      "unidadeEnsino": "2",
      "unidadeFisica": "001",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "PUBL",
      "nomeCurso": "Publicidade e Propaganda",
      "serie": "8",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 9,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2014,
      "periodo": 0,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "JOR",
      "nomeCurso": "JORNALISMO",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2014/0"
    },
    {
      "total": 7,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2014,
      "periodo": 0,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "JOR",
      "nomeCurso": "JORNALISMO",
      "serie": "3",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2014/0"
    },
    {
      "total": 7,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2014,
      "periodo": 0,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "JOR",
      "nomeCurso": "JORNALISMO",
      "serie": "4",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2014/0"
    },
    {
      "total": 2,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 9,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "2",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 19,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "3",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 13,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "4",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 18,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "5",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 12,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "6",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 16,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "7",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 13,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "8",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 20,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "9",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 11,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "10",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 6,
      "unidadeEnsino": "2",
      "unidadeFisica": "002",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ARQ",
      "nomeCurso": "ARQUITETURA",
      "serie": "12",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 1,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "MBA",
      "descricao": "MBA",
      "curso": "MKT-MBA",
      "nomeCurso": "MBA EM MARKETING",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 6,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 11,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "2",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 16,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "3",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 27,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "4",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 26,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "5",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 27,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "6",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 32,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "7",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 20,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "201",
      "nomeCurso": "Administração | Seriado",
      "serie": "8",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 15,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "202",
      "nomeCurso": "Pedagogia | Por Crédito Presencial",
      "serie": "2",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 12,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "202",
      "nomeCurso": "Pedagogia | Por Crédito Presencial",
      "serie": "3",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 22,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "202",
      "nomeCurso": "Pedagogia | Por Crédito Presencial",
      "serie": "4",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 26,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "202",
      "nomeCurso": "Pedagogia | Por Crédito Presencial",
      "serie": "5",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 24,
      "unidadeEnsino": "2",
      "unidadeFisica": "003",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "202",
      "nomeCurso": "Pedagogia | Por Crédito Presencial",
      "serie": "6",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 3,
      "unidadeEnsino": "20",
      "unidadeFisica": "20",
      "ano": 2017,
      "periodo": 0,
      "tipo": "TEC",
      "descricao": "TÉCNICO",
      "curso": "2002",
      "nomeCurso": "US MAMA",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/0"
    },
    {
      "total": 1,
      "unidadeEnsino": "3",
      "unidadeFisica": "10",
      "ano": 2017,
      "periodo": 1,
      "tipo": "MESTRADO",
      "descricao": "MESTRADO",
      "curso": "MS-001",
      "nomeCurso": "MESTRADO EM COMUNICAÇÃO",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 3,
      "unidadeEnsino": "4",
      "unidadeFisica": "null",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "Evento-TCN-010",
      "nomeCurso": "Inglês - Básico",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 1,
      "unidadeEnsino": "4",
      "unidadeFisica": "null",
      "ano": 2017,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "Evento-TCN-013",
      "nomeCurso": "Espanhol - Básico",
      "serie": "1",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2017/1"
    },
    {
      "total": 10,
      "unidadeEnsino": "5",
      "unidadeFisica": "005",
      "ano": 2016,
      "periodo": 1,
      "tipo": "SUP",
      "descricao": "SUPERIOR",
      "curso": "ENG_ELETRICA",
      "nomeCurso": "Engenharia Elétrica",
      "serie": "2",
      "tipoHist": "MATRICULADOS",
      "anoPeriodo": "2016/1"
    }
  ]
/* 
function groupByTipoHist() {
	return _(data)
			.groupBy(eva => eva.tipo)
			.map((objs, key) => ({
				'tipoHist': key,
				'anoPeriodo':objs[0].anoPeriodo,
				'total': _.sumBy(objs, 'total')
			})).value();
} */
function groupByMatriculados() {
    return _(data)
            .filter(filter_by => filter_by.tipoHist == 'MATRICULADOS')
			.groupBy(eva => eva.anoPeriodo)
			.map((objs, key) => ({
                'anoPeriodo': key,
                'tipoHist' : 'MATRICULADOS',
				'total': _.sumBy(objs, 'total')
			})).value();
}
function groupByEvadidos() {
    return _(data)
            .filter(filter_by => filter_by.tipoHist == 'EVADIDOS')
			.groupBy(eva => eva.anoPeriodo)
			.map((objs, key) => ({
                'anoPeriodo': key,
                'tipoHist' : 'EVADIDOS',
				'total': _.sumBy(objs, 'total')
			})).value();
}
console.log(_.orderBy(groupByMatriculados(),['anoPeriodo']));
var obj1 = _.orderBy(groupByMatriculados(),['anoPeriodo']);
console.log(_.orderBy(groupByEvadidos(),['anoPeriodo']));
var obj2 = _.orderBy(groupByEvadidos(),['anoPeriodo']);

function merge(obj1, obj2) {
    var obj3;
    obj3 = obj1;
    for(let index = 0, len = obj2.length;index < len;index++) {
        obj3.push(obj2[index]);
    }
    return _(obj3)
            .groupBy(eva => eva.anoPeriodo)
            .map((objs, key) => ({
                'anoPeriodo': key,
                'objs' : objs,
                'total': _.sumBy(objs, 'total')
            })).value();
}

console.log(_.orderBy(merge(obj1,obj2),['anoPeriodo']));

