data = [
    {
      "CURSO": "2001",
      "VAGAS": null,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "20",
      "NOME_UNIDADE_ENSINO": "CETRUS",
      "UNIDADE_FISICA": "20",
      "NOME_UNIDADE_FISICA": "CETRUS",
      "CONCURSO": null,
      "ANO": 2017,
      "PERIODO": 0,
      "ANO_PERIODO": "2017/0",
      "PROGRESSO": 0
    },
    {
      "CURSO": "201",
      "VAGAS": 50,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "2",
      "NOME_UNIDADE_ENSINO": "Faculdade",
      "UNIDADE_FISICA": "001",
      "NOME_UNIDADE_FISICA": "Campus I",
      "CONCURSO": "PS2017",
      "ANO": 2017,
      "PERIODO": 1,
      "ANO_PERIODO": "2017/1",
      "PROGRESSO": 0
    },
    {
      "CURSO": "201",
      "VAGAS": 50,
      "INSCRITOS": 1,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "2",
      "NOME_UNIDADE_ENSINO": "Faculdade",
      "UNIDADE_FISICA": "001",
      "NOME_UNIDADE_FISICA": "Campus I",
      "CONCURSO": "PS2017_2",
      "ANO": 2017,
      "PERIODO": 2,
      "ANO_PERIODO": "2017/2",
      "PROGRESSO": "2.00"
    },
    {
      "CURSO": "CineB",
      "VAGAS": null,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "4",
      "NOME_UNIDADE_ENSINO": "Cursos Livres",
      "UNIDADE_FISICA": null,
      "NOME_UNIDADE_FISICA": null,
      "CONCURSO": null,
      "ANO": 2017,
      "PERIODO": 2,
      "ANO_PERIODO": "2017/2",
      "PROGRESSO": 0
    },
    {
      "CURSO": "CineE",
      "VAGAS": null,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "4",
      "NOME_UNIDADE_ENSINO": "Cursos Livres",
      "UNIDADE_FISICA": null,
      "NOME_UNIDADE_FISICA": null,
      "CONCURSO": null,
      "ANO": 2017,
      "PERIODO": 2,
      "ANO_PERIODO": "2017/2",
      "PROGRESSO": 0
    },
    {
      "CURSO": "EF2",
      "VAGAS": 400,
      "INSCRITOS": 0,
      "CONVOCADOS": 1,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "1",
      "NOME_UNIDADE_ENSINO": "Colégio",
      "UNIDADE_FISICA": "009",
      "NOME_UNIDADE_FISICA": "Campus IX",
      "CONCURSO": "EBPS2017",
      "ANO": 2017,
      "PERIODO": 1,
      "ANO_PERIODO": "2017/1",
      "PROGRESSO": 0
    },
    {
      "CURSO": "EFI",
      "VAGAS": 500,
      "INSCRITOS": 1,
      "CONVOCADOS": 1,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "1",
      "NOME_UNIDADE_ENSINO": "Colégio",
      "UNIDADE_FISICA": "009",
      "NOME_UNIDADE_FISICA": "Campus IX",
      "CONCURSO": "EBPS2017",
      "ANO": 2017,
      "PERIODO": 1,
      "ANO_PERIODO": "2017/1",
      "PROGRESSO": "0.20"
    },
    {
      "CURSO": "Enfermagem",
      "VAGAS": 50,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "2",
      "NOME_UNIDADE_ENSINO": "Faculdade",
      "UNIDADE_FISICA": "10",
      "NOME_UNIDADE_FISICA": "Campus X",
      "CONCURSO": "PS2017",
      "ANO": 2017,
      "PERIODO": 1,
      "ANO_PERIODO": "2017/1",
      "PROGRESSO": "0.20"
    },
    {
      "CURSO": "Enfermagem",
      "VAGAS": 50,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "2",
      "NOME_UNIDADE_ENSINO": "Faculdade",
      "UNIDADE_FISICA": "10",
      "NOME_UNIDADE_FISICA": "Campus X",
      "CONCURSO": "PS2017_2",
      "ANO": 2017,
      "PERIODO": 2,
      "ANO_PERIODO": "2017/2",
      "PROGRESSO": "0.20"
    },
    {
      "CURSO": "FotoD",
      "VAGAS": null,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "4",
      "NOME_UNIDADE_ENSINO": "Cursos Livres",
      "UNIDADE_FISICA": null,
      "NOME_UNIDADE_FISICA": null,
      "CONCURSO": null,
      "ANO": 2017,
      "PERIODO": 2,
      "ANO_PERIODO": "2017/2",
      "PROGRESSO": 0
    },
    {
      "CURSO": "LEEsp.",
      "VAGAS": null,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "4",
      "NOME_UNIDADE_ENSINO": "Cursos Livres",
      "UNIDADE_FISICA": null,
      "NOME_UNIDADE_FISICA": null,
      "CONCURSO": null,
      "ANO": 2017,
      "PERIODO": 2,
      "ANO_PERIODO": "2017/2",
      "PROGRESSO": 0
    },
    {
      "CURSO": "LEFranc.",
      "VAGAS": null,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "4",
      "NOME_UNIDADE_ENSINO": "Cursos Livres",
      "UNIDADE_FISICA": null,
      "NOME_UNIDADE_FISICA": null,
      "CONCURSO": null,
      "ANO": 2017,
      "PERIODO": 2,
      "ANO_PERIODO": "2017/2",
      "PROGRESSO": 0
    },
    {
      "CURSO": "LEInglês",
      "VAGAS": null,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "4",
      "NOME_UNIDADE_ENSINO": "Cursos Livres",
      "UNIDADE_FISICA": null,
      "NOME_UNIDADE_FISICA": null,
      "CONCURSO": null,
      "ANO": 2017,
      "PERIODO": 2,
      "ANO_PERIODO": "2017/2",
      "PROGRESSO": 0
    },
    {
      "CURSO": "PUBL",
      "VAGAS": 50,
      "INSCRITOS": 1,
      "CONVOCADOS": 4,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "2",
      "NOME_UNIDADE_ENSINO": "Faculdade",
      "UNIDADE_FISICA": "001",
      "NOME_UNIDADE_FISICA": "Campus I",
      "CONCURSO": "PS2017",
      "ANO": 2017,
      "PERIODO": 1,
      "ANO_PERIODO": "2017/1",
      "PROGRESSO": "2.00"
    },
    {
      "CURSO": "PUBL",
      "VAGAS": 50,
      "INSCRITOS": 0,
      "CONVOCADOS": 0,
      "MATRICULADOS": 0,
      "UNIDADE_ENSINO": "2",
      "NOME_UNIDADE_ENSINO": "Faculdade",
      "UNIDADE_FISICA": "001",
      "NOME_UNIDADE_FISICA": "Campus I",
      "CONCURSO": "PS2017_2",
      "ANO": 2017,
      "PERIODO": 2,
      "ANO_PERIODO": "2017/2",
      "PROGRESSO": "2.00"
    }
  ]
  function groupByCurso() {
    return _(data)
			.groupBy(eva => eva.CURSO)
			.map((objs, key) => ({
                'CURSO': key,
                'VAGAS': _.sumBy(objs, 'VAGAS'),
                'INSCRITOS': _.sumBy(objs, 'INSCRITOS'),
                'CONVOCADOS': _.sumBy(objs, 'CONVOCADOS'),
                'MATRICULADOS': _.sumBy(objs, 'MATRICULADOS'),
                'NOME_UNIDADE_ENSINO' : objs[0].NOME_UNIDADE_ENSINO,
                'NOME_UNIDADE_FISICA' : objs[0].NOME_UNIDADE_FISICA,
                'PROGRESSO':retornaProgresso(_.sumBy(objs, 'VAGAS'), _.sumBy(objs, 'INSCRITOS')),
                'object': objs
			})).value();
}
function retornaProgresso(val1, val2) {
    if(isNaN(val1 / val2)) {
      return 0;
  } else if(val1 !== 0 && val2 !== 0){
      return parseFloat((val2 / val1) * 100).toFixed(2);
  }
}
console.log(groupByCurso());